#!/usr/bin/env bash
set -euo pipefail

# Locked ConFiQA all-subset protocol with a uniform 120-row component discovery
# screen. This reruns QA/MR/MC under one provenance chain before site or random
# interface controls are attached.
#
# Fixed windows:
#   train source: official rows [0, 300)
#   pair split: val when prepared row index % 5 == 0
#   component discovery: first 120 train pairs
#   head refine: first 24 train pairs
#   actuator training cap: train 240 / val 60
#   held-out generation: official rows [1000, 1500)

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

OUT="${OUT:-data_ckplug/cast_confiqa_all3_disc120_heldout500_v0}"
GPU="${GPU:-0}"
TASKS="${TASKS:-qa mr mc}"

TRAIN_SOURCE_ROWS="${TRAIN_SOURCE_ROWS:-300}"
VAL_MOD="${VAL_MOD:-5}"
TRAIN_ROWS="${TRAIN_ROWS:-240}"
VAL_ROWS="${VAL_ROWS:-60}"
EPOCHS="${EPOCHS:-2}"
MLP_EPOCHS="${MLP_EPOCHS:-$EPOCHS}"
HEAD_EPOCHS="${HEAD_EPOCHS:-$EPOCHS}"
MLP_TRAIN_ROWS="${MLP_TRAIN_ROWS:-$TRAIN_ROWS}"
MLP_VAL_ROWS="${MLP_VAL_ROWS:-$VAL_ROWS}"
HEAD_TRAIN_ROWS="${HEAD_TRAIN_ROWS:-$TRAIN_ROWS}"
HEAD_VAL_ROWS="${HEAD_VAL_ROWS:-$VAL_ROWS}"

DISCOVERY_ROWS="${DISCOVERY_ROWS:-120}"
DISCOVERY_TOPK_MLP="${DISCOVERY_TOPK_MLP:-4}"
DISCOVERY_TOPK_ATTN_LAYERS="${DISCOVERY_TOPK_ATTN_LAYERS:-4}"
HEAD_SCAN_ROWS="${HEAD_SCAN_ROWS:-24}"
HEAD_SCAN_FACTORS="${HEAD_SCAN_FACTORS:-0.0,1.5}"
HEAD_TOPK="${HEAD_TOPK:-4}"
HEAD_REFINE_EVAL_ROWS="${HEAD_REFINE_EVAL_ROWS:-1}"

EVAL_SOURCE_START="${EVAL_SOURCE_START:-1000}"
EVAL_SOURCE_ROWS="${EVAL_SOURCE_ROWS:-500}"
EVAL_ROWS="${EVAL_ROWS:-500}"
EVAL_SPLIT="${EVAL_SPLIT:-all}"

RUN_CONTEXT_DPO="${RUN_CONTEXT_DPO:-1}"
RUN_BASE_PROMPTS="${RUN_BASE_PROMPTS:-1}"
AUTO_TUNE="${AUTO_TUNE:-0}"
INSTALL_DEPS="${INSTALL_DEPS:-0}"
DOWNLOAD_MODELS="${DOWNLOAD_MODELS:-0}"
FOREGROUND="${FOREGROUND:-0}"

mkdir -p "$OUT"
cat > "$OUT/locked_protocol.env" <<EOF
OUT=$OUT
GPU=$GPU
TASKS=$TASKS
TRAIN_SOURCE_ROWS=$TRAIN_SOURCE_ROWS
VAL_MOD=$VAL_MOD
TRAIN_ROWS=$TRAIN_ROWS
VAL_ROWS=$VAL_ROWS
MLP_TRAIN_ROWS=$MLP_TRAIN_ROWS
MLP_VAL_ROWS=$MLP_VAL_ROWS
HEAD_TRAIN_ROWS=$HEAD_TRAIN_ROWS
HEAD_VAL_ROWS=$HEAD_VAL_ROWS
DISCOVERY_ROWS=$DISCOVERY_ROWS
DISCOVERY_TOPK_MLP=$DISCOVERY_TOPK_MLP
DISCOVERY_TOPK_ATTN_LAYERS=$DISCOVERY_TOPK_ATTN_LAYERS
HEAD_SCAN_ROWS=$HEAD_SCAN_ROWS
HEAD_SCAN_FACTORS=$HEAD_SCAN_FACTORS
HEAD_TOPK=$HEAD_TOPK
HEAD_REFINE_EVAL_ROWS=$HEAD_REFINE_EVAL_ROWS
EVAL_SOURCE_START=$EVAL_SOURCE_START
EVAL_SOURCE_ROWS=$EVAL_SOURCE_ROWS
EVAL_ROWS=$EVAL_ROWS
EVAL_SPLIT=$EVAL_SPLIT
RUN_CONTEXT_DPO=$RUN_CONTEXT_DPO
AUTO_TUNE=$AUTO_TUNE
EOF

OUT="$OUT" \
GPU="$GPU" \
TASKS="$TASKS" \
TRAIN_SOURCE_ROWS="$TRAIN_SOURCE_ROWS" \
VAL_MOD="$VAL_MOD" \
TRAIN_ROWS="$TRAIN_ROWS" \
VAL_ROWS="$VAL_ROWS" \
EPOCHS="$EPOCHS" \
MLP_EPOCHS="$MLP_EPOCHS" \
HEAD_EPOCHS="$HEAD_EPOCHS" \
MLP_TRAIN_ROWS="$MLP_TRAIN_ROWS" \
MLP_VAL_ROWS="$MLP_VAL_ROWS" \
HEAD_TRAIN_ROWS="$HEAD_TRAIN_ROWS" \
HEAD_VAL_ROWS="$HEAD_VAL_ROWS" \
DISCOVERY_ROWS="$DISCOVERY_ROWS" \
DISCOVERY_TOPK_MLP="$DISCOVERY_TOPK_MLP" \
DISCOVERY_TOPK_ATTN_LAYERS="$DISCOVERY_TOPK_ATTN_LAYERS" \
HEAD_SCAN_ROWS="$HEAD_SCAN_ROWS" \
HEAD_SCAN_FACTORS="$HEAD_SCAN_FACTORS" \
HEAD_TOPK="$HEAD_TOPK" \
HEAD_REFINE_EVAL_ROWS="$HEAD_REFINE_EVAL_ROWS" \
EVAL_SOURCE_START="$EVAL_SOURCE_START" \
EVAL_SOURCE_ROWS="$EVAL_SOURCE_ROWS" \
EVAL_ROWS="$EVAL_ROWS" \
EVAL_SPLIT="$EVAL_SPLIT" \
RUN_CONTEXT_DPO="$RUN_CONTEXT_DPO" \
RUN_BASE_PROMPTS="$RUN_BASE_PROMPTS" \
AUTO_TUNE="$AUTO_TUNE" \
INSTALL_DEPS="$INSTALL_DEPS" \
DOWNLOAD_MODELS="$DOWNLOAD_MODELS" \
FOREGROUND="$FOREGROUND" \
bash scripts/bootstrap_cast_confiqa_all3_tuna.sh
